import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { DepthChart } from './DepthChart.js';
import { StatsPanel } from './StatsPanel.js';
import { useEngineFeed } from './useEngineFeed.js';
const FEED_URL = import.meta.env.VITE_FEED_URL ?? 'ws://localhost:8080/feed';
export function App() {
    const { book, trades, stats, priceHistory, connected, nextRetryInMs } = useEngineFeed(FEED_URL);
    return (_jsxs("main", { children: [_jsxs("header", { children: [_jsx("h1", { children: "trading-sim" }), _jsx("span", { className: connected ? 'pill ok' : 'pill ko', children: connected ? 'live' : 'disconnected' }), !connected && nextRetryInMs !== null && (_jsxs("span", { className: "banner", children: ["Reconnecting in ", Math.max(1, Math.ceil(nextRetryInMs / 1000)), "s\u2026"] }))] }), _jsxs("section", { className: "grid", children: [_jsxs("article", { children: [_jsx("h2", { children: "Depth" }), _jsx(DepthChart, { bids: book?.bids ?? [], asks: book?.asks ?? [] })] }), _jsxs("article", { children: [_jsx("h2", { children: "Recent trades" }), _jsx("ol", { className: "tape", children: trades.map((t) => (_jsxs("li", { children: [_jsx("code", { children: new Date(t.ts).toISOString().slice(11, 19) }), _jsxs("span", { children: [t.qty, " @ ", t.price.toFixed(2)] })] }, `${t.ts}-${t.buy}-${t.sell}`))) })] }), _jsxs("article", { children: [_jsx("h2", { children: "Order book" }), book === null ? (_jsx("p", { children: "Waiting for snapshot\u2026" })) : (_jsxs("div", { className: "book", children: [_jsxs("table", { children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Bid qty" }), _jsx("th", { children: "Bid" })] }) }), _jsx("tbody", { children: book.bids.map(([price, qty]) => (_jsxs("tr", { children: [_jsx("td", { children: qty }), _jsx("td", { className: "bid", children: price.toFixed(2) })] }, `b-${price}`))) })] }), _jsxs("table", { children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Ask" }), _jsx("th", { children: "Ask qty" })] }) }), _jsx("tbody", { children: book.asks.map(([price, qty]) => (_jsxs("tr", { children: [_jsx("td", { className: "ask", children: price.toFixed(2) }), _jsx("td", { children: qty })] }, `a-${price}`))) })] })] }))] }), _jsx(StatsPanel, { stats: stats, priceHistory: priceHistory })] })] }));
}
